apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grist
spec:
  releaseName: grist
  chart:
    spec:
      chart: grist
      sourceRef:
        kind: HelmRepository
        name: grist
        namespace: flux-system
      version: "7.0.31"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: grist-values