---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: grist
  name: grist
  namespace: grist
spec:
  ports:
    - name: "8484"
      port: 8484
      targetPort: 8484
  selector:
    io.kompose.service: grist
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: grist
  name: grist
  namespace: grist
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grist
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/grist-default: "true"
        io.kompose.service: grist
    spec:
      containers:
        - image: gristlabs/grist
          name: grist
          ports:
            - containerPort: 8484
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: grist-default
  namespace: grist
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/grist-default: "true"
  podSelector:
    matchLabels:
      io.kompose.network/grist-default: "true"

